(()=>{"use strict";
const API="https://irratigis-api.pages.dev";
const ZONE={west:-5.0,south:42.3,east:-0.8,north:44.0};
let firmsLayer=null,firmsLoading=false,statusEl=null,meteosatLayer=null,meteosatBusy=false,meteosatTimer=null;
const token=()=>window.IrratiGISAuth?.getToken?.()||"";
const getMap=()=>window.IrratiGISMap||null;
function status(text,type="info"){const map=getMap();if(!map)return;if(!statusEl){statusEl=document.createElement("div");statusEl.id="irratiFirmsStatus";statusEl.style.cssText="position:absolute;left:10px;bottom:10px;z-index:1000;padding:7px 10px;border-radius:9px;background:#fff;box-shadow:0 2px 10px rgba(0,0,0,.2);font:800 12px system-ui;color:#345243;max-width:520px;pointer-events:none";map.getContainer().appendChild(statusEl)}statusEl.textContent=text;statusEl.style.color=type==="error"?"#a12626":type==="ok"?"#176b43":"#345243";statusEl.style.display="block"}
function getFirmsLayer(){if(!firmsLayer&&typeof L!=="undefined")firmsLayer=L.featureGroup();window.IrratiGISFirmsLayer=firmsLayer;return firmsLayer}
function coords(f){let lat=f?.latitude??f?.lat??f?.y,lon=f?.longitude??f?.lon??f?.lng??f?.x;if((lat==null||lon==null)&&Array.isArray(f?.geometry?.coordinates)){[lon,lat]=f.geometry.coordinates}lat=Number(lat);lon=Number(lon);return Number.isFinite(lat)&&Number.isFinite(lon)?[lat,lon]:null}
function inZone(c){return c&&c[0]>=ZONE.south&&c[0]<=ZONE.north&&c[1]>=ZONE.west&&c[1]<=ZONE.east}
function items(d){return Array.isArray(d?.fires)?d.fires:Array.isArray(d?.detections)?d.detections:Array.isArray(d?.data)?d.data:Array.isArray(d?.features)?d.features:[]}
function ensureRows(){const map=getMap(),list=document.querySelector(".leaflet-control-layers-overlays"),firms=getFirmsLayer();if(!map||!list||!firms)return;let row=list.querySelector(".irrati-firms-layer-row");if(!row){row=document.createElement("label");row.className="irrati-firms-layer-row";row.style.display="block";const input=document.createElement("input");input.type="checkbox";input.className="leaflet-control-layers-selector";row.appendChild(input);const span=document.createElement("span");span.textContent=" 🚨 NASA FIRMS";row.appendChild(span);list.appendChild(row);input.addEventListener("change",()=>{if(input.checked){firms.addTo(map);loadFirms()}else{map.removeLayer(firms);status("NASA FIRMS: itzalita")}})}const fInput=row.querySelector("input");if(fInput)fInput.checked=map.hasLayer(firms);let mrow=list.querySelector(".irrati-meteosat-layer-row");if(!mrow){mrow=document.createElement("label");mrow.className="irrati-meteosat-layer-row";mrow.style.display="block";const input=document.createElement("input");input.type="checkbox";input.className="leaflet-control-layers-selector";mrow.appendChild(input);const span=document.createElement("span");span.textContent=" 🌍 Meteosat - incendios (zona norte)";mrow.appendChild(span);list.appendChild(mrow);input.addEventListener("change",()=>{if(input.checked){if(!meteosatLayer)meteosatLayer=L.layerGroup().addTo(map);else meteosatLayer.addTo(map);refreshMeteosat()}else{removeMeteosat();status("Meteosat: itzalita")}});input.checked=!!meteosatLayer} }
async function loadFirms(){if(firmsLoading)return;const map=getMap(),firms=getFirmsLayer(),t=token();if(!map||!firms||!t)return;firmsLoading=true;status("NASA FIRMS: datuak kargatzen…");try{const r=await fetch(`${API}/api/firms?days=5`,{headers:{Authorization:`Bearer ${t}`}});const raw=await r.text();let d={};try{d=JSON.parse(raw)}catch(_){throw new Error("FIRMS erantzuna ez da JSON")}if(!r.ok)throw new Error(d.detail||d.error||`HTTP ${r.status}`);const arr=items(d);firms.clearLayers();let count=0;for(const f of arr){const c=coords(f);if(!inZone(c))continue;const m=L.circleMarker(c,{radius:8,weight:2,color:"#8b0000",fillColor:"#ff3b00",fillOpacity:.95});m.bindPopup(`<strong>🛰️ NASA FIRMS</strong><br>Data: ${f.acqDate||f.acq_date||"—"}<br>Ordua: ${f.acqTime||f.acq_time||"—"}<br>Satelitea: ${f.satellite||f.satellite_name||"—"}<br>Konfiantza: ${f.confidence??f.confidence_pct??"—"}<br>FRP: ${f.frp??"—"} MW<br>Koordenatuak: ${c[0].toFixed(5)}, ${c[1].toFixed(5)}`);firms.addLayer(m);count++}status(count?`NASA FIRMS: ${count} detecciones en la zona`:`NASA FIRMS: 0 detecciones en la zona`,count?"ok":"info")}catch(e){console.error(e);status(`NASA FIRMS: ERROREA — ${e.message||e}`,"error")}finally{firmsLoading=false}}
const WMS="https://adaguc.lsasvcs.ipma.pt//adagucserver",DATASET="MSG-FRP";
function round15(d){const x=new Date(d);x.setUTCMinutes(Math.floor(x.getUTCMinutes()/15)*15,0,0);return x}
function fallbackTime(){return new Date(round15(Date.now()-30*60*1000)).toISOString()}
async function latestMeteosat(){try{const u=`${WMS}?dataset=${DATASET}&SERVICE=WMS&REQUEST=GetCapabilities&_irrati=${Date.now()}`,r=await fetch(u,{cache:"no-store",mode:"cors"});if(!r.ok)throw new Error(`GetCapabilities HTTP ${r.status}`);const xml=new DOMParser().parseFromString(await r.text(),"text/xml"),layers=[...xml.getElementsByTagName("Layer")],target=layers.find(l=>/FRP-PIXEL/i.test(l.textContent||""));if(!target)throw new Error("No se encontró FRP-PIXEL");const name=[...target.children].find(e=>e.localName==="Name")?.textContent?.trim()||"FRP",dim=[...target.children].find(e=>(e.localName==="Dimension"||e.localName==="Extent")&&e.getAttribute("name")?.toLowerCase()==="time");let v=dim?.textContent?.trim().split(/[;,]/).filter(Boolean).pop()||"";if(v.includes("/"))v=v.split("/")[1];const dt=new Date(v);return{name,time:Number.isFinite(dt.getTime())?dt.toISOString():fallbackTime()}}catch(e){console.warn("Meteosat capabilities",e);return{name:"FRP",time:fallbackTime()}}}
function removeMeteosat(){const map=getMap();if(meteosatLayer&&map)map.removeLayer(meteosatLayer);meteosatLayer=null;if(meteosatTimer)clearTimeout(meteosatTimer);meteosatTimer=null}
async function refreshMeteosat(){const map=getMap();if(!map||!meteosatLayer||meteosatBusy)return;meteosatBusy=true;try{const info=await latestMeteosat(),bounds=L.latLngBounds([[ZONE.south,ZONE.west],[ZONE.north,ZONE.east]]),size=map.getSize(),p=new URLSearchParams({SERVICE:"WMS",REQUEST:"GetMap",VERSION:"1.1.1",LAYERS:info.name,STYLES:"",FORMAT:"image/png",TRANSPARENT:"TRUE",SRS:"EPSG:4326",BBOX:`${ZONE.west},${ZONE.south},${ZONE.east},${ZONE.north}`,WIDTH:String(Math.max(800,Math.min(1600,Math.round(size.x)))),HEIGHT:String(Math.max(500,Math.min(1100,Math.round(size.y)))),TIME:info.time,dataset:DATASET,_irrati:Date.now()});const url=`${WMS}?${p}`;const img=new Image();img.onload=()=>{if(meteosatLayer){const old=meteosatLayer;meteosatLayer=L.layerGroup().addTo(map);L.imageOverlay(url,bounds,{opacity:.98,interactive:false,zIndex:650,attribution:"© EUMETSAT / LSA SAF"}).addTo(meteosatLayer);map.removeLayer(old);window.IrratiGISMeteosatLayer=meteosatLayer}status(`Meteosat: ${info.time.slice(0,16).replace("T"," ")} UTC · zona norte · OK`,"ok");meteosatBusy=false};img.onerror=()=>{status("Meteosat: GetMap ERROR","error");meteosatBusy=false};img.src=url}catch(e){status(`Meteosat: ERROR — ${e.message||e}`,"error");meteosatBusy=false}}
function boot(){const map=getMap();if(!map||typeof L==="undefined")return setTimeout(boot,500);ensureRows();window.IrratiGISFirms={get layer(){return getFirmsLayer()},load:loadFirms,open:()=>{const l=getFirmsLayer();l.addTo(map);loadFirms()}};window.IrratiGISFirePopup={openFirms:()=>window.IrratiGISFirms.open(),loadBurnsIntoLayer:boot,hookLayerControl:boot};window.IrratiGISMeteosat={open:async()=>{if(!meteosatLayer)meteosatLayer=L.layerGroup().addTo(map);await refreshMeteosat()},refresh:refreshMeteosat};map.on("moveend zoomend",()=>{if(meteosatLayer)refreshMeteosat()});setInterval(()=>{if(meteosatLayer)refreshMeteosat()},15*60*1000);setTimeout(()=>{ensureRows();loadFirms()},1200)}
boot();
})();