(()=>{
"use strict";
const API="https://irratigis-api.pages.dev",FIRMS_ZONE={west:-5,south:42.3,east:-0.8,north:44},FIRMS_DAYS=5,WMS="https://adaguc.lsasvcs.ipma.pt//adagucserver?dataset=MSG-FRP",METEOSAT_LAYER="MSG:FRP-PIXEL";
let firmsLoading=false,statusEl=null,legend=null,meteosatLayers=[],meteosatBusy=false,meteosatHours=72;
const map=()=>window.IrratiGISMap||null,token=()=>window.IrratiGISAuth?.getToken?.()||"";
function status(t,type="info"){const m=map();if(!m)return;if(!statusEl){statusEl=document.createElement("div");statusEl.id="irratiFirmsStatus";statusEl.style.cssText="position:absolute;left:10px;bottom:10px;z-index:1000;padding:7px 10px;border-radius:9px;background:#fff;box-shadow:0 2px 10px rgba(0,0,0,.2);font:800 12px system-ui;color:#345243;max-width:560px;pointer-events:none";m.getContainer().appendChild(statusEl)}statusEl.textContent=t;statusEl.style.color=type==="error"?"#a12626":type==="ok"?"#176b43":"#345243";statusEl.style.display="block"}
function firmsLayer(){if(window.IrratiGISFirmsLayer)return window.IrratiGISFirmsLayer;if(typeof L!=="undefined")return window.IrratiGISFirmsLayer=L.featureGroup();return null}
function items(d){return Array.isArray(d?.fires)?d.fires:Array.isArray(d?.detections)?d.detections:Array.isArray(d?.data)?d.data:Array.isArray(d?.features)?d.features:[]}
function field(f,...ks){const p=f?.properties||{};for(const k of ks){if(f?.[k]!=null&&f[k]!=="")return f[k];if(p?.[k]!=null&&p[k]!=="")return p[k]}return null}
function coords(f){const p=f?.properties||{};let lat=f?.latitude??f?.lat??f?.y??p.latitude??p.lat??p.y,lon=f?.longitude??f?.lon??f?.lng??f?.x??p.longitude??p.lon??p.lng??p.x;if((lat==null||lon==null)&&Array.isArray(f?.geometry?.coordinates))[lon,lat]=f.geometry.coordinates;lat=Number(lat);lon=Number(lon);return Number.isFinite(lat)&&Number.isFinite(lon)?[lat,lon]:null}
function inZone(c,z){return c&&c[0]>=z.south&&c[0]<=z.north&&c[1]>=z.west&&c[1]<=z.east}
function fireDate(f){let d=field(f,"acqDate","acq_date"),t=String(field(f,"acqTime","acq_time")??"").replace(/\D/g,"");if(/^\d{8}$/.test(d))d=`${d.slice(0,4)}-${d.slice(4,6)}-${d.slice(6,8)}`;if(d&&t){t=t.padStart(4,"0").slice(0,4);return new Date(`${d}T${t.slice(0,2)}:${t.slice(2)}:00Z`)}const x=new Date(d||"");return Number.isFinite(x.getTime())?x:null}
function age(f){const d=fireDate(f),h=d?Math.max(0,(Date.now()-d)/36e5):Infinity;if(h<6)return["< 6 h","#d7191c","#8b0000",11];if(h<24)return["6–24 h","#f57c00","#a94f00",10];if(h<72)return["1–3 días","#fbc02d","#9a7400",9];return["3–5 días","#757575","#4b4b4b",8]}
function ensureLegend(m){if(legend||!m)return;legend=L.control({position:"bottomright"});legend.onAdd=()=>{const d=L.DomUtil.create("div");d.style.cssText="background:#fff;padding:8px 10px;border-radius:9px;box-shadow:0 1px 5px rgba(0,0,0,.3);font:700 11px system-ui;line-height:1.65";d.innerHTML="<b>NASA FIRMS · antigüedad</b><br>🔴 &lt; 6 h<br>🟠 6–24 h<br>🟡 1–3 días<br>⚪ 3–5 días";return d};legend.addTo(m)}
async function loadFirms(){if(firmsLoading)return;const m=map(),layer=firmsLayer(),t=token();if(!m||!layer||!t)return;firmsLoading=true;status(`NASA FIRMS: cargando últimos ${FIRMS_DAYS} días…`);try{const r=await fetch(`${API}/api/firms?days=${FIRMS_DAYS}`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}),d=JSON.parse(await r.text());if(!r.ok)throw Error(d.detail||d.error||`HTTP ${r.status}`);const fs=items(d).map(f=>({f,c:coords(f)})).filter(x=>inZone(x.c,FIRMS_ZONE));layer.clearLayers();ensureLegend(m);for(const x of fs){const[a,fill,stroke,rad]=age(x.f),sz=rad*2,ic=L.divIcon({className:"irrati-firms-dot",html:`<span style="display:block;border-radius:50%;box-sizing:border-box;width:${sz}px;height:${sz}px;background:${fill};border:2px solid ${stroke};box-shadow:0 1px 5px #555,0 0 0 2px #fff"></span>`,iconSize:[sz,sz],iconAnchor:[rad,rad]}),mk=L.marker(x.c,{icon:ic,zIndexOffset:2000});mk.bindPopup(`<b>🛰️ NASA FIRMS</b><br><b>Antigüedad:</b> ${a}<br><b>Fecha:</b> ${field(x.f,"acqDate","acq_date")||"—"}<br><b>Hora:</b> ${field(x.f,"acqTime","acq_time")||"—"} UTC<br><b>Satélite:</b> ${field(x.f,"satellite","satellite_name")||"—"}<br><b>Confianza:</b> ${field(x.f,"confidence","confidence_pct")??"—"}<br><b>FRP:</b> ${field(x.f,"frp")??"—"} MW<br><b>Coordenadas:</b> ${x.c[0].toFixed(5)}, ${x.c[1].toFixed(5)}<br><small>⚠️ Detección térmica por satélite; no implica por sí sola un incendio confirmado.</small>`);layer.addLayer(mk)}status(`NASA FIRMS: ${fs.length} detecciones en la zona · últimos ${FIRMS_DAYS} días`,fs.length?"ok":"info")}catch(e){console.error(e);status(`NASA FIRMS: ERROR — ${e.message||e}`,"error")}finally{firmsLoading=false}}
function clearMeteosat(){const m=map();meteosatLayers.forEach(x=>{try{if(m)m.removeLayer(x)}catch{}});meteosatLayers=[];window.IrratiGISMeteosatLayer=null}
function times(hours){const end=new Date();end.setUTCSeconds(0,0);end.setUTCMinutes(Math.floor(end.getUTCMinutes()/15)*15);const out=[],step=3*36e5;for(let t=end.getTime()-hours*36e5;t<=end.getTime();t+=step)out.push(new Date(t));return out}
function wmsOptions(time,version="1.1.1",style=""){const o={layers:METEOSAT_LAYER,styles:style,format:"image/png",transparent:true,version,attribution:"© EUMETSAT / LSA SAF",opacity:.7};o.srs="EPSG:4326";if(time)o.time=time.toISOString();return o}
function waitTile(layer,timeout=12000){return new Promise(resolve=>{let done=false,timer=setTimeout(()=>{if(done)return;done=true;resolve(false)},timeout);layer.once("tileload",()=>{if(done)return;done=true;clearTimeout(timer);resolve(true)});layer.once("tileerror",()=>{if(done)return;done=true;clearTimeout(timer);resolve(false)})})}
async function addMeteosatLayer(time,opacity){const m=map();if(!m)return false;const candidates=[["1.1.1",""] ,["1.3.0",""]];for(const [version,style] of candidates){const opts=wmsOptions(time,version,style);if(version==="1.3.0")delete opts.srs;const layer=L.tileLayer.wms(WMS,opts);layer.setOpacity(opacity);const ready=waitTile(layer);layer.addTo(m);const ok=await ready;if(ok){meteosatLayers.push(layer);return true}m.removeLayer(layer)}return false}
async function refreshMeteosat(){const m=map();if(!m||meteosatBusy)return;meteosatBusy=true;clearMeteosat();try{status("Meteosat: probando WMS FRP-PIXEL…");const current=await addMeteosatLayer(null,.9);if(!current){status(`Meteosat: el WMS no ha podido cargar ${METEOSAT_LAYER}. FIRMS sigue operativo.` ,"error");return}const ts=times(meteosatHours).slice(0,-1);let hist=0;for(const t of ts){if(await addMeteosatLayer(t,.45))hist++}status(`Meteosat: WMS operativo · actual + ${hist} históricos · ${meteosatHours} h`,hist?"ok":"info")}catch(e){console.error(e);status(`Meteosat: ERROR WMS — ${e.message||e}`,"error")}finally{meteosatBusy=false}}
function setHours(h){meteosatHours=h;document.querySelectorAll(".irrati-meteosat-tools button").forEach(b=>b.classList.toggle("active",+b.dataset.h===h));if(document.querySelector(".irrati-meteosat-layer-row input")?.checked)refreshMeteosat()}
function rows(){const m=map(),list=document.querySelector(".leaflet-control-layers-overlays");if(!m||!list)return;let fr=list.querySelector(".irrati-firms-layer-row");if(!fr){fr=document.createElement("label");fr.className="irrati-firms-layer-row";const i=document.createElement("input");i.type="checkbox";i.className="leaflet-control-layers-selector";fr.append(i," 🚨 NASA FIRMS · 5 días");list.append(fr);i.onchange=()=>i.checked?(firmsLayer().addTo(m),loadFirms()):m.removeLayer(firmsLayer())}fr.querySelector("input").checked=m.hasLayer(firmsLayer());let mr=list.querySelector(".irrati-meteosat-layer-row");if(!mr){mr=document.createElement("label");mr.className="irrati-meteosat-layer-row";const i=document.createElement("input");i.type="checkbox";i.className="leaflet-control-layers-selector";mr.append(i," 🌍 Meteosat - incendios (zona norte)");list.append(mr);const tools=document.createElement("div");tools.className="irrati-meteosat-tools";[[24,"24 h"],[48,"48 h"],[72,"72 h"]].forEach(([h,l])=>{const b=document.createElement("button");b.type="button";b.dataset.h=h;b.textContent=l;if(h===meteosatHours)b.classList.add("active");b.onclick=e=>{e.preventDefault();e.stopPropagation();setHours(h)};tools.append(b)});list.append(tools);const n=document.createElement("small");n.textContent="FRP-PIXEL · SEVIRI/MSG · WMS · vista del mapa";n.style.cssText="display:block;margin:3px 0 5px 25px;color:#667;font:10px system-ui";list.append(n);i.onchange=()=>i.checked?refreshMeteosat():(clearMeteosat(),status("Meteosat: desactivado"))}}
function boot(){const m=map();if(!m||typeof L==="undefined")return setTimeout(boot,500);rows();window.IrratiGISFirms={get layer(){return firmsLayer()},load:loadFirms,open:()=>{firmsLayer().addTo(m);loadFirms()}};window.IrratiGISFirePopup={openFirms:()=>window.IrratiGISFirms.open(),loadBurnsIntoLayer:boot,hookLayerControl:boot};window.IrratiGISMeteosat={open:refreshMeteosat,refresh:refreshMeteosat};setTimeout(()=>{rows();loadFirms()},1200);m.on("moveend zoomend",()=>{if(meteosatLayers.length&&!meteosatBusy)refreshMeteosat()})}
boot();
})();
