(()=>{
"use strict";
const OVERPASS="https://overpass-api.de/api/interpreter";
const CACHE=new Map();
const VEGETATION=new Set(["forest","wood","scrub","heath","fell","farmland","farmyard","meadow","orchard","vineyard","grassland","grass","allotments","greenfield","plant_nursery","greenhouse_horticulture","animal_keeping"]);
const INDUSTRIAL=new Set(["industrial","quarry","brownfield","works","kiln","plant","chimney","storage_tank","silo","power","generator","substation","landfill"]);
const URBAN=new Set(["residential","retail","commercial","institutional","parking","construction","depot"]);
const esc=s=>String(s??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
function distance(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180,la=a.lat*Math.PI/180,lb=b.lat*Math.PI/180,x=Math.sin(dLat/2)**2+Math.sin(dLon/2)**2*Math.cos(la)*Math.cos(lb);return 2*R*Math.asin(Math.sqrt(x));}
function tagsOf(e){return e?.tags||{};}
function centerOf(e){if(Number.isFinite(e?.lat)&&Number.isFinite(e?.lon))return{lat:e.lat,lon:e.lon};if(Number.isFinite(e?.center?.lat)&&Number.isFinite(e?.center?.lon))return{lat:e.center.lat,lon:e.center.lon};return null;}
async function query(lat,lon){const key=`${lat.toFixed(3)},${lon.toFixed(3)}`;if(CACHE.has(key))return CACHE.get(key);const q=`[out:json][timeout:12];(nwr(around:1000,${lat},${lon})[landuse~"^(forest|meadow|farmland|farmyard|orchard|vineyard|grassland|industrial|commercial|residential|retail|brownfield|quarry|greenfield|allotments)$"];nwr(around:1000,${lat},${lon})[natural~"^(wood|scrub|heath|grassland)$"];nwr(around:1000,${lat},${lon})[industrial];nwr(around:1000,${lat},${lon})[man_made~"^(works|kiln|chimney|storage_tank|silo|plant|power|generator|substation|landfill)$"];nwr(around:1000,${lat},${lon})[place~"^(hamlet|isolated_dwelling|village)$"];);out center tags;`;
const r=await fetch(OVERPASS,{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:q,cache:"no-store"});if(!r.ok)throw new Error(`OSM HTTP ${r.status}`);const d=await r.json();CACHE.set(key,d.elements||[]);return d.elements||[];}
function buildContext(lat,lon,elements){const p={lat,lon};let vegetation=[],industrial=[],urban=[],rural=[];for(const e of elements){const t=tagsOf(e),c=centerOf(e),d=c?distance(p,c):Infinity;const land=t.landuse,natural=t.natural,ind=t.industrial,mm=t.man_made,place=t.place;if(VEGETATION.has(land)||VEGETATION.has(natural))vegetation.push({d,t});if(INDUSTRIAL.has(land)||INDUSTRIAL.has(ind)||INDUSTRIAL.has(mm))industrial.push({d,t});if(URBAN.has(land))urban.push({d,t});if(place==="hamlet"||place==="isolated_dwelling"||land==="farmyard")rural.push({d,t});}
const nearest=(arr)=>arr.length?Math.min(...arr.map(x=>x.d)):null;const labels=(arr,key)=>[...new Set(arr.filter(x=>x.t[key]).map(x=>x.t[key]))].slice(0,5);
return{parcel:"unknown",vegetation:vegetation.length>0,industrial:industrial.length>0,ruralSettlement:rural.length>0,urban:urban.length>0,nearestIndustrialM:nearest(industrial)!=null?Math.round(nearest(industrial)*1000):null,vegetationTags:[...new Set([...labels(vegetation,"landuse"),...labels(vegetation,"natural")])].slice(0,6),industrialTags:[...new Set([...labels(industrial,"landuse"),...labels(industrial,"industrial"),...labels(industrial,"man_made")])].slice(0,6),urbanTags:labels(urban,"landuse"),ruralTags:[...new Set(rural.map(x=>x.t.place||x.t.landuse).filter(Boolean))].slice(0,5)};}
function panel(c){const veg=c.vegetation?`Sí${c.vegetationTags.length?` · ${esc(c.vegetationTags.join(", "))}`:""}`:"No claro";const ind=c.industrial?`Sí${c.nearestIndustrialM!=null?` · elemento más próximo ≈ ${c.nearestIndustrialM} m`:""}${c.industrialTags.length?` · ${esc(c.industrialTags.join(", "))}`:""}`:"No claro";const rural=c.ruralSettlement?`Sí${c.ruralTags.length?` · ${esc(c.ruralTags.join(", "))}`:""}`:"No claro";const urban=c.urban?`Sí · ${esc(c.urbanTags.join(", "))}`:"No claro";return `<div class="irrati-firms-context"><div class="irrati-firms-context-title">Contexto geográfico</div><div><b>Parcela catastral:</b> Pendiente de integración</div><div><b>Vegetación/cobertura OSM:</b> ${veg}</div><div><b>Actividad industrial OSM:</b> ${ind}</div><div><b>Entorno urbano OSM:</b> ${urban}</div><div><b>Entorno rural/disperso:</b> ${rural}</div><div class="irrati-firms-context-note">Estos datos son señales de contexto, no una clasificación del origen de la detección.</div><div class="irrati-firms-context-pending">Interpretación automática: todavía no aplicada.</div></div>`;}
async function enrichPopup(e){const popup=e?.popup,source=e?.sourceTarget;if(!popup||!source||source.__irratiContextBusy)return;const ll=source.getLatLng?.();if(!ll)return;source.__irratiContextBusy=true;const el=popup.getElement?.();if(el){const old=el.querySelector(".irrati-firms-context");if(old)return;const body=el.querySelector(".leaflet-popup-content");if(body){const box=document.createElement("div");box.className="irrati-firms-context";box.innerHTML=`<div class="irrati-firms-context-title">Contexto geográfico</div><div>Consultando OpenStreetMap…</div>`;body.appendChild(box);}}
try{const elements=await query(ll.lat,ll.lng);const c=buildContext(ll.lat,ll.lng,elements);const el2=popup.getElement?.()?.querySelector(".irrati-firms-context");if(el2)el2.outerHTML=panel(c);}catch(err){const el2=popup.getElement?.()?.querySelector(".irrati-firms-context");if(el2)el2.innerHTML=`<div class="irrati-firms-context-title">Contexto geográfico</div><div>No se pudo consultar OpenStreetMap ahora.</div><div class="irrati-firms-context-note">La detección FIRMS no cambia por este error.</div>`;console.warn("FIRMS contexto OSM:",err)}finally{source.__irratiContextBusy=false;}}
function boot(){const map=window.IrratiGISMap;if(!map||typeof L==="undefined")return setTimeout(boot,500);if(document.getElementById("irrati-firms-context-style"))return;const s=document.createElement("style");s.id="irrati-firms-context-style";s.textContent=".irrati-firms-context{margin-top:8px;padding:8px 9px;background:#f7faf8;border:1px solid #dce5df;border-radius:9px;font-size:11px;line-height:1.55}.irrati-firms-context-title{font-weight:900;color:#176b43;margin-bottom:3px}.irrati-firms-context-note{margin-top:5px;color:#65736b;font-size:10px}.irrati-firms-context-pending{margin-top:4px;font-weight:800;color:#65736b}";document.head.appendChild(s);map.on("popupopen",enrichPopup);}
boot();
})();
