(()=>{
"use strict";
const OVERPASS="https://overpass-api.de/api/interpreter";
const CACHE=new Map();
const VEGETATION=new Set(["forest","wood","scrub","heath","fell","farmland","farmyard","meadow","orchard","vineyard","grassland","grass","allotments","greenfield","plant_nursery","greenhouse_horticulture","animal_keeping"]);
const INDUSTRIAL=new Set(["industrial","quarry","brownfield","works","kiln","plant","chimney","storage_tank","silo","power","generator","substation","landfill"]);
const URBAN=new Set(["residential","retail","commercial","institutional","parking","construction","depot"]);
let installedMap=null,classifierPromise=null;
const esc=s=>String(s??"").replace(/[&<>\\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\\":"\\\\","\"":"&quot;"}[c]??c));
function distance(a,b){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180,la=a.lat*Math.PI/180,lb=b.lat*Math.PI/180,x=Math.sin(dLat/2)**2+Math.sin(dLon/2)**2*Math.cos(la)*Math.cos(lb);return 2*R*Math.asin(Math.sqrt(x));}
function tagsOf(e){return e?.tags||{}}
function centerOf(e){if(Number.isFinite(e?.lat)&&Number.isFinite(e?.lon))return{lat:e.lat,lon:e.lon};if(Number.isFinite(e?.center?.lat)&&Number.isFinite(e?.center?.lon))return{lat:e.center.lat,lon:e.center.lon};return null}
async function query(lat,lon){const key=`${lat.toFixed(3)},${lon.toFixed(3)}`;if(CACHE.has(key))return CACHE.get(key);const q=`[out:json][timeout:8];(nwr(around:1000,${lat},${lon})[landuse];nwr(around:1000,${lat},${lon})[natural];nwr(around:1000,${lat},${lon})[industrial];nwr(around:1000,${lat},${lon})[man_made];nwr(around:1000,${lat},${lon})[place];);out center tags;`;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),4500);const p=fetch(OVERPASS,{method:"POST",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:q,cache:"no-store",signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error(`OSM HTTP ${r.status}`);const d=await r.json(),e=d.elements||[];CACHE.set(key,e);return e}).finally(()=>clearTimeout(timer));CACHE.set(key,p);return p}
function buildContext(lat,lon,elements){const p={lat,lon},vegetation=[],industrial=[],urban=[],rural=[],tags=[];for(const e of elements){const t=tagsOf(e),c=centerOf(e),d=c?distance(p,c):Infinity,land=t.landuse,natural=t.natural,ind=t.industrial,mm=t.man_made,place=t.place,veg=VEGETATION.has(land)||VEGETATION.has(natural),indHit=INDUSTRIAL.has(land)||INDUSTRIAL.has(ind)||INDUSTRIAL.has(mm),urb=URBAN.has(land);for(const [k,v] of Object.entries(t))tags.push(`${k}=${v}`.toLowerCase());if(veg)vegetation.push({d,t});if(indHit)industrial.push({d,t});if(urb)urban.push({d,t});if(place==="hamlet"||place==="isolated_dwelling"||place==="village"||land==="farmyard")rural.push({d,t})}const nearest=arr=>arr.length?Math.min(...arr.map(x=>x.d)):null,ni=nearest(industrial),nv=nearest(vegetation),nu=nearest(urban),immediateIndustrial=ni!=null&&ni<=.18,interfaceForest=nv!=null&&nv<=.30&&nu!=null&&nu<=.35;return{parcel:"unknown",parcelUrban:false,parcelRural:false,vegetation:nv!=null&&nv<=.30,industrial:immediateIndustrial,urban:nu!=null&&nu<=.35,ruralSettlement:rural.length>0,nearestIndustrialM:immediateIndustrial?Math.round(ni*1000):null,nearestIndustrialMeters:ni!=null?ni*1000:null,nearestForestMeters:nv!=null?nv*1000:null,vegetationTags:[...new Set(vegetation.filter(x=>x.d<=.30).flatMap(x=>[x.t.landuse,x.t.natural]).filter(Boolean))].slice(0,6),industrialTags:immediateIndustrial?[...new Set(industrial.filter(x=>x.d<=.18).flatMap(x=>[x.t.landuse,x.t.industrial,x.t.man_made]).filter(Boolean))].slice(0,6):[],urbanTags:[...new Set(urban.filter(x=>x.d<=.35).map(x=>x.t.landuse).filter(Boolean))].slice(0,6),ruralTags:[...new Set(rural.map(x=>x.t.place||x.t.landuse).filter(Boolean))].slice(0,5),interfaceForest,localForest:nv!=null&&nv<=.30,tags:[...new Set(tags)]}}
function panel(c){const veg=c.vegetation?`Sí${c.vegetationTags.length?` · ${esc(c.vegetationTags.join(", "))}`:""}`:"No claro";const ind=c.industrial?`Sí${c.nearestIndustrialM!=null?` · elemento industrial inmediato ≈ ${c.nearestIndustrialM} m`:""}${c.industrialTags.length?` · ${esc(c.industrialTags.join(", "))}`:""}`:"No industrial inmediato";const rural=c.ruralSettlement?`Sí${c.ruralTags.length?` · ${c.ruralTags.join(", ")}`:""}`:"No claro";const urban=c.urban?`Sí · ${esc(c.urbanTags.join(", "))}`:"No claro";return `<div class="irrati-firms-context"><div class="irrati-firms-context-title">🌍 Contexto geográfico</div><div><b>Parcela catastral:</b> Pendiente de integración</div><div><b>Vegetación/cobertura OSM:</b> ${veg}</div><div><b>Actividad industrial en el foco:</b> ${ind}</div><div><b>Entorno urbano OSM:</b> ${urban}</div><div><b>Entorno rural/disperso:</b> ${rural}</div><div><b>Interfaz urbano-forestal:</b> ${c.interfaceForest?"Sí":"No clara"}</div><div class="irrati-firms-context-note">La industria solo se considera factor de origen cuando existe un elemento industrial a ≤180 m del foco. Objetos más lejanos no contaminan la clasificación.</div></div>`}
function loadClassifier(){if(window.IrratiGISFirmsClassifier)return Promise.resolve(window.IrratiGISFirmsClassifier);if(classifierPromise)return classifierPromise;classifierPromise=new Promise(resolve=>{let done=false;const finish=()=>{if(done)return;done=true;resolve(window.IrratiGISFirmsClassifier||null)};const s=document.createElement("script");s.src="firms-classifier.js?v=20260911-industrial3";s.onload=()=>finish();s.onerror=()=>finish();document.head.appendChild(s);setTimeout(finish,4000)});return classifierPromise}
function fireDataFromPopup(source){return source?.__firmsData||source?.options?.__firmsData||null}
async function classifyFallback(source,ll,context){const body=source?.getPopup?.()?.getElement?.()?.querySelector?.(".leaflet-popup-content");if(!body)return;const box=body.querySelector(".irrati-firms-class");if(!box||!/(clasificaci|classific)/i.test(box.textContent||""))return;const f=fireDataFromPopup(source);if(!f)return;const cls=await loadClassifier();if(!cls?.classify)return;const result=cls.classify(f,context||{});if(!result)return;box.innerHTML=`${esc(result.label||"Clasificado")} ${result.score!=null?`· Score ${result.score}/100`:""}`;source.__irratiContextClassification=result}
async function enrichPopup(e){const popup=e?.popup,source=e?.sourceTarget||e?.target;if(!popup||!source||source.__irratiContextBusy)return;setTimeout(async()=>{const el=popup.getElement?.(),body=el?.querySelector(".leaflet-popup-content");if(!body||!/NASA FIRMS/i.test(body.textContent||"")||body.querySelector(".irrati-firms-context"))return;const ll=source.getLatLng?.()||popup.getLatLng?.();if(!ll)return;source.__irratiContextBusy=true;const box=document.createElement("div");box.className="irrati-firms-context";box.innerHTML=`<div class="irrati-firms-context-title">🌍 Contexto geográfico</div><div>Consultando OpenStreetMap…</div>`;body.appendChild(box);let c=null;try{const elements=await query(ll.lat,ll.lng);c=buildContext(ll.lat,ll.lng,elements);if(box.isConnected)box.outerHTML=panel(c);if(popup.update)popup.update();}catch(err){c={parcel:"unknown",parcelUrban:false,parcelRural:false,vegetation:false,industrial:false,urban:false,nearestIndustrialMeters:null,nearestForestMeters:null,localForest:false,tags:[]};if(box.isConnected)box.innerHTML=`<div class="irrati-firms-context-title">🌍 Contexto geográfico</div><div>No se pudo consultar OpenStreetMap ahora.</div><div class="irrati-firms-context-note">La detección FIRMS no cambia por este error.</div>`;console.warn("FIRMS contexto OSM:",err)}finally{try{await classifyFallback(source,ll,c)}catch(err){console.warn("FIRMS clasificación fallback:",err)}source.__irratiContextBusy=false}},0)}
function attachLayer(layer){if(!layer||typeof layer.on!=="function"||typeof layer.getPopup!=="function"||layer.__irratiContextAttached)return;const p=layer.getPopup?.();if(!p)return;const content=typeof p.getContent==="function"?p.getContent():p._content;if(!/NASA FIRMS/i.test(String(content||"")))return;layer.__irratiContextAttached=true;layer.on("popupopen",enrichPopup)}
function install(){const map=window.IrratiGISMap;if(!map||typeof L==="undefined")return false;if(installedMap===map)return true;if(!document.getElementById("irrati-firms-context-style")){const s=document.createElement("style");s.id="irrati-firms-context-style";s.textContent=".irrati-firms-context{margin-top:8px;padding:8px 9px;background:#f7faf8;border:1px solid #dce5df;border-radius:9px;font-size:11px;line-height:1.55}.irrati-firms-context-title{font-weight:900;color:#176b43;margin-bottom:3px}.irrati-firms-context-note{margin-top:5px;color:#65736b;font-size:10px}";document.head.appendChild(s)}installedMap=map;map.eachLayer(attachLayer);map.on("layeradd",e=>attachLayer(e.layer));map.on("popupopen",enrichPopup);return true}
function boot(){if(install())return;setTimeout(boot,500)}
boot();
window.IrratiGISFirmsContext={version:"20260911-02",query,enrichPopup};
})();