(()=>{
"use strict";
/* Meteosat FRP-PIXEL: detecciones sobre toda Europa. Sin simbología de antigüedad. */
const API="https://irratigis-api.pages.dev/api/meteosat",WMS="https://irratigis-api.pages.dev/api/meteosat-wms?slot=",HOUR=3600000,REFRESH=900000,LATENCY=35*60000,HISTORY=5*24*HOUR;
const BBOX={west:-25,south:34,east:45,north:72};
let map=null,enabled=false,loading=false,timer=null,h5=null,h5Promise=null;const files=new Map();
const $=id=>document.getElementById(id),getMap=()=>window.IrratiGISMap||((typeof window.map!=="undefined")?window.map:null);
function r15(d){const x=new Date(d);x.setUTCSeconds(0,0);x.setUTCMinutes(Math.floor(x.getUTCMinutes()/15)*15);return x}
function rh(d){const x=new Date(d);x.setUTCMinutes(0,0,0);return x}
function fmt(d){return new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Madrid"}).format(d)}
function slot(d){const p=n=>String(n).padStart(2,"0");return `${d.getUTCFullYear()}${p(d.getUTCMonth()+1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(d.getUTCMinutes())}`}
function status(t,type="info"){const e=$("irratiMeteosatStatus");if(e){e.textContent=t;e.style.color=type==="error"?"#a12626":type==="ok"?"#176b43":"#52645a"}}
function pane(){if(!map.getPane("meteosatPane")){const p=map.createPane("meteosatPane");p.style.zIndex=700}}
function panel(){if($("irratiMeteosatPanel"))return;const c=document.createElement("div");c.id="irratiMeteosatPanel";c.className="irrati-meteosat-panel leaflet-control";c.style.display="none";c.innerHTML=`<div class="irrati-meteosat-head"><strong>★ Meteosat · FRP</strong><button id="irratiMeteosatClose" type="button" aria-label="Cerrar panel">×</button></div><div class="irrati-meteosat-sub">Incendios detectados (tiempo real)</div><div class="irrati-meteosat-time" id="irratiMeteosatTime">—</div><div id="irratiMeteosatStatus" class="irrati-meteosat-status">Meteosat apagado</div><div class="irrati-meteosat-note">LSA SAF / EUMETSAT · FRP-PIXEL · Europa</div>`;map.getContainer().appendChild(c);$("irratiMeteosatClose").onclick=()=>{const input=document.querySelector(".irrati-meteosat-layer-row input");if(input){input.checked=false;input.dispatchEvent(new Event("change",{bubbles:true}))}else toggle(false)}}
function loadH5(){if(h5Promise)return h5Promise;h5Promise=import("https://cdn.jsdelivr.net/npm/h5wasm@0.10.3/dist/esm/hdf5_hl.js").then(async m=>{await m.default.ready;h5=m.default;return h5});return h5Promise}
function get(o,n){try{return o.get(n)}catch{return null}}
function find(root,names){const wanted=new Set(names),seen=new Set();function walk(o,d){if(!o||d>4||seen.has(o))return null;seen.add(o);let ks=[];try{ks=o.keys()}catch{return null}for(const k of ks){const ch=get(o,k);if(!ch)continue;if(wanted.has(String(k).toUpperCase()))return ch;const z=walk(ch,d+1);if(z)return z}return null}return walk(root,0)}
function value(ds){try{return ds?.value}catch{return null}}
function parse(f,slotDate){const lat=value(find(f,["LATITUDE"])),lon=value(find(f,["LONGITUDE"]));if(!lat||!lon)return[];const frp=value(find(f,["FRP"])),conf=value(find(f,["FIRE_CONFIDENCE"])),area=value(find(f,["PIXEL_SIZE"])),acq=value(find(f,["ACQTIME"])),out=[];for(let i=0;i<lat.length;i++){const la=Number(lat[i])/100,lo=Number(lon[i])/100;if(!Number.isFinite(la)||!Number.isFinite(lo)||la<BBOX.south||la>BBOX.north||lo<BBOX.west||lo>BBOX.east)continue;const t=new Date(slotDate);if(acq&&Number.isFinite(Number(acq[i]))){const q=Number(acq[i]);if(q>=0&&q<2400)t.setUTCHours(Math.floor(q/100),q%100,0,0)}out.push({lat:la,lon:lo,time:t,frp:frp?Number(frp[i])/10:null,conf:conf?Number(conf[i])/100:null,area:area?Number(area[i])/100:null})}return out}
async function wmsImage(d){const r=await fetch(`${WMS}${slot(d)}`,{cache:"no-store"});if(!r.ok)throw new Error(`WMS HTTP ${r.status}`);return r.blob()}
async function wmsRows(d){const blob=await wmsImage(d),bmp=await createImageBitmap(blob),w=1000,h=600,cv=document.createElement("canvas");cv.width=w;cv.height=h;const ctx=cv.getContext("2d",{willReadFrequently:true});ctx.drawImage(bmp,0,0);bmp.close();const data=ctx.getImageData(0,0,w,h).data,step=4,cells=new Set();for(let y=0;y<h;y+=step)for(let x=0;x<w;x+=step){const i=(y*w+x)*4,a=data[i+3],rr=data[i],gg=data[i+1],bb=data[i+2],mx=Math.max(rr,gg,bb),mn=Math.min(rr,gg,bb);if(a>30&&((rr+gg+bb)<735||(mx-mn)>45||rr>180||gg>120||bb>120))cells.add(`${Math.floor(x/step)},${Math.floor(y/step)}`)}const seen=new Set(),out=[];for(const key of cells){if(seen.has(key))continue;const q=[key];seen.add(key);let sx=0,sy=0,n=0;while(q.length){const z=q.pop().split(",").map(Number),cx=z[0],cy=z[1];sx+=cx;sy+=cy;n++;for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++){const nk=`${cx+dx},${cy+dy}`;if(cells.has(nk)&&!seen.has(nk)){seen.add(nk);q.push(nk)}}}const px=sx/n*step+step/2,py=sy/n*step+step/2,lon=BBOX.west+px/w*(BBOX.east-BBOX.west),lat=BBOX.north-py/h*(BBOX.north-BBOX.south);if(lat>=BBOX.south&&lat<=BBOX.north&&lon>=BBOX.west&&lon<=BBOX.east)out.push({lat,lon,time:new Date(d),frp:null,conf:null,area:null})}return out}
function render(rows){const g=L.layerGroup();rows.forEach(x=>{const size=24,icon=L.divIcon({className:"irrati-meteosat-star",html:`<span class="irrati-meteosat-star-inner">★</span>`,iconSize:[size,size],iconAnchor:[size/2,size/2],popupAnchor:[0,-size/2]});const m=L.marker([x.lat,x.lon],{icon,pane:"meteosatPane",zIndexOffset:5000,title:"Meteosat FRP-PIXEL"});const frp=x.frp==null?"—":`${x.frp.toFixed(1)} MW`,conf=x.conf==null?"—":`${Math.round(x.conf)}%`,area=x.area==null?"—":`${x.area.toFixed(2)} km²`;m.bindPopup(`<strong>★ Meteosat FRP-PIXEL</strong><br>Ubicación: ${x.lat.toFixed(4)}, ${x.lon.toFixed(4)}<br>Fecha/hora: ${fmt(x.time)}<br>FRP: ${frp}<br>Confianza: ${conf}<br>Área efectiva: ${area}`);g.addLayer(m)});g.addTo(map);return g}
async function fetchSlot(d){const k=d.getTime();if(files.has(k))return files.get(k).count;let rows=null,source="";try{const r=await fetch(`${API}?slot=${slot(d)}`,{cache:"no-store"});if(r.ok){const ab=await r.arrayBuffer(),M=await h5.ready,name=`frp_${k}.h5`;M.FS.writeFile(name,new Uint8Array(ab));const f=new h5.File(name,"r");rows=parse(f,d);f.close();try{M.FS.unlink(name)}catch{}source="HDF5"}}catch(e){console.warn("Meteosat HDF5",slot(d),e)}if(rows===null){try{rows=await wmsRows(d);source="WMS"}catch(e){console.warn("Meteosat WMS",slot(d),e);return-1}}const layer=render(rows);files.set(k,{count:rows.length,layer,slot:new Date(d),source});return rows.length}
function purge(){const cut=Date.now()-HISTORY;files.forEach((v,k)=>{if(k<cut){try{map.removeLayer(v.layer)}catch{}files.delete(k)}})}
function fitEurope(){if(!map)return;map.fitBounds([[BBOX.south,BBOX.west],[BBOX.north,BBOX.east]],{padding:[24,24],animate:false,maxZoom:5})}
function fixFirmsPanel(){const mapc=map?.getContainer?.();if(!mapc)return;const target=mapc.querySelector(".leaflet-bottom.leaflet-left"),met=$("irratiMeteosatPanel");if(!target||!met)return;document.querySelectorAll(".leaflet-control").forEach(el=>{if(el!==met&&el.textContent.includes("NASA FIRMS · antigüedad")){if(el.parentElement!==target)target.appendChild(el);el.style.marginLeft="10px";el.style.marginBottom="8px";el.style.float="none";met.style.bottom=`${el.offsetHeight+18}px`;}})}
async function load(){if(loading||!enabled)return;loading=true;try{status("Meteosat: conectando con FRP-PIXEL…");await loadH5();const latest=r15(new Date(Date.now()-LATENCY)),hour=rh(latest),slots=[latest];for(let t=hour.getTime()-HOUR;t>=hour.getTime()-HISTORY;t-=HOUR)slots.push(new Date(t));let done=0,det=0,miss=0,cursor=0;const worker=async()=>{while(cursor<slots.length&&enabled){const d=slots[cursor++],n=await fetchSlot(d);done++;if(n<0)miss++;else det+=n;if(done%5===0||done===slots.length)status(`Meteosat: ${done}/${slots.length} horas · ${det} detecciones${miss?` · ${miss} sin datos`:""}`)}};await Promise.all([worker(),worker(),worker(),worker()]);purge();$("irratiMeteosatTime").textContent=`Última adquisición: ${fmt(latest)} local`;status(`Meteosat: ${Array.from(files.values()).reduce((n,v)=>n+v.count,0)} detecciones visibles${miss?` · ${miss} horas sin datos`:""}`,"ok")}catch(e){console.error(e);status(`Meteosat: error — ${e.message||e}`,"error")}finally{loading=false}}
function schedule(){if(timer)clearTimeout(timer);const now=Date.now(),next=(Math.floor(now/REFRESH)+1)*REFRESH+4000;timer=setTimeout(async()=>{timer=null;if(enabled){await load();schedule()}},Math.max(5000,next-now))}
async function toggle(on){enabled=!!on;panel();$("irratiMeteosatPanel").style.display=on?"block":"none";if(!on){if(timer)clearTimeout(timer);files.forEach(v=>{try{map.removeLayer(v.layer)}catch{}});files.clear();timer=null;window.IrratiGISMeteosatLayer=null;status("Meteosat apagado");return}pane();fitEurope();await load();fixFirmsPanel();window.IrratiGISMeteosatLayer={toggle};schedule()}
function row(){document.querySelectorAll(".leaflet-control-layers-overlays").forEach(list=>{if(list.querySelector(".irrati-meteosat-layer-row"))return;const r=document.createElement("label");r.className="irrati-meteosat-layer-row";r.style.display="block";const i=document.createElement("input");i.type="checkbox";i.className="leaflet-control-layers-selector";i.checked=enabled;i.onchange=()=>toggle(i.checked);const s=document.createElement("span");s.textContent=" ★ Meteosat FRP";r.append(i,s);list.appendChild(r)})}
function styles(){if($("irratiMeteosatStyle"))return;const s=document.createElement("style");s.id="irratiMeteosatStyle";s.textContent=`.irrati-meteosat-panel{position:absolute;left:8px;bottom:78px;z-index:1002;width:min(250px,calc(100vw - 16px));background:#fff;border-radius:9px;box-shadow:0 2px 10px rgba(0,0,0,.2);padding:8px;font:11px system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#1c2d24}.irrati-meteosat-head{display:flex;justify-content:space-between;align-items:center}.irrati-meteosat-head strong{font-size:12px}.irrati-meteosat-head button{border:0;background:#eef3ef;border-radius:6px;padding:2px 6px;cursor:pointer}.irrati-meteosat-sub,.irrati-meteosat-note{color:#65736b;margin-top:3px}.irrati-meteosat-time{margin-top:6px;font-weight:800;color:#334b3e}.irrati-meteosat-status{margin-top:4px}.irrati-meteosat-note{font-size:9px;line-height:1.2}.irrati-meteosat-star{background:transparent!important;border:0!important}.irrati-meteosat-star-inner{display:block!important;visibility:visible!important;opacity:1!important;width:30px;height:30px;color:#000;font-size:30px;line-height:25px;text-align:center;text-shadow:-1px -1px 0 #fff,1px -1px 0 #fff,-1px 1px 0 #fff,1px 1px 0 #fff,0 1px 4px rgba(0,0,0,.45)}`;document.head.appendChild(s)}
function loadTrackEditor(){if(document.getElementById("irratiTrackEditorScript"))return;const s=document.createElement("script");s.id="irratiTrackEditorScript";s.src="track-editor.js?v=20260907-01";s.defer=true;document.head.appendChild(s)}
function loadFirmsContext(){if(document.getElementById("irratiFirmsContextScript"))return;const s=document.createElement("script");s.id="irratiFirmsContextScript";s.src="firms-context.js?v=20260908-01";s.defer=true;document.head.appendChild(s)}
function boot(){map=getMap();if(!map){setTimeout(boot,500);return}styles();panel();row();fixFirmsPanel();loadTrackEditor();loadFirmsContext();new MutationObserver(()=>{row();fixFirmsPanel()}).observe(document.body,{childList:true,subtree:true});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();