(()=>{
"use strict";
/* Meteosat FRP-PIXEL: puntos horarios + último slot disponible, coloreados por antigüedad. NASA FIRMS no se modifica. */
const API="https://irratigis-api.pages.dev/api/meteosat",HOUR=3600000,REFRESH=900000,LATENCY=35*60000,HISTORY=5*24*HOUR;
const BBOX={west:-5,south:42.3,east:-0.8,north:44},C={fresh:"#e31a1c",recent:"#ff8c00",old:"#ffd21f",oldest:"#8b8b8b"};
const SCALE={FRP:10,LATITUDE:100,LONGITUDE:100,FIRE_CONFIDENCE:100,PIXEL_SIZE:100};
let map=null,enabled=false,loading=false,timer=null,h5=null,h5Promise=null;const files=new Map();
const $=id=>document.getElementById(id);
function getMap(){return window.IrratiGISMap||((typeof window.map!=="undefined")?window.map:null)}
function r15(d){const x=new Date(d);x.setUTCSeconds(0,0);x.setUTCMinutes(Math.floor(x.getUTCMinutes()/15)*15);return x}
function rh(d){const x=new Date(d);x.setUTCMinutes(0,0,0);return x}
function fmt(d){return new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Madrid"}).format(d)}
function age(t){const h=Math.max(0,(Date.now()-t)/HOUR);if(h<6)return{c:C.fresh,l:"0–6 h"};if(h<24)return{c:C.recent,l:"6–24 h"};if(h<72)return{c:C.old,l:"1–3 d"};return{c:C.oldest,l:"3–5 d"}}
function slot(d){const p=n=>String(n).padStart(2,"0");return `${d.getUTCFullYear()}${p(d.getUTCMonth()+1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(d.getUTCMinutes())}`}
function status(t,type="info"){const e=$("irratiMeteosatStatus");if(e){e.textContent=t;e.style.color=type==="error"?"#a12626":type==="ok"?"#176b43":"#52645a"}}
function pane(){if(!map.getPane("meteosatPane")){const p=map.createPane("meteosatPane");p.style.zIndex=620}}
function panel(){if($("irratiMeteosatPanel"))return;const c=document.createElement("div");c.id="irratiMeteosatPanel";c.className="irrati-meteosat-panel leaflet-control";c.innerHTML=`<div class="irrati-meteosat-head"><strong>🛰️ Meteosat · FRP</strong><button id="irratiMeteosatClose" type="button">×</button></div><div class="irrati-meteosat-sub">Detecciones · antigüedad</div><div class="irrati-meteosat-legend"><span><i class="fresh">★</i>0–6 h</span><span><i class="recent">★</i>6–24 h</span><span><i class="old">★</i>1–3 d</span><span><i class="oldest">★</i>3–5 d</span></div><div class="irrati-meteosat-time" id="irratiMeteosatTime">—</div><div id="irratiMeteosatStatus" class="irrati-meteosat-status">Meteosat apagado</div><div class="irrati-meteosat-note">LSA SAF / EUMETSAT · FRP-PIXEL LSA-502 · producto cada 15 min. Histórico representado por horas.</div>`;map.getContainer().appendChild(c);$("irratiMeteosatClose").onclick=()=>toggle(false)}
function loadH5(){if(h5Promise)return h5Promise;h5Promise=import("https://cdn.jsdelivr.net/npm/h5wasm@0.10.3/dist/esm/hdf5_hl.js").then(async m=>{await m.default.ready;h5=m.default;return h5});return h5Promise}
function get(o,n){try{return o.get(n)}catch{return null}}
function find(root,names){const wanted=new Set(names),seen=new Set();function walk(o,d){if(!o||d>4||seen.has(o))return null;seen.add(o);let ks=[];try{ks=o.keys()}catch{return null}for(const k of ks){const ch=get(o,k);if(!ch)continue;if(wanted.has(String(k).toUpperCase()))return ch;const z=walk(ch,d+1);if(z)return z}return null}return walk(root,0)}
function value(ds){try{return ds?.value}catch{return null}}
function s(n,v){return Number(v)/(SCALE[n]||1)}
function parse(f,slotDate){const lat=value(find(f,["LATITUDE"])),lon=value(find(f,["LONGITUDE"]));if(!lat||!lon)return[];const frp=value(find(f,["FRP"])),conf=value(find(f,["FIRE_CONFIDENCE"])),area=value(find(f,["PIXEL_SIZE"])),acq=value(find(f,["ACQTIME"])),out=[];for(let i=0;i<lat.length;i++){const la=s("LATITUDE",lat[i]),lo=s("LONGITUDE",lon[i]);if(!Number.isFinite(la)||!Number.isFinite(lo)||la<BBOX.south||la>BBOX.north||lo<BBOX.west||lo>BBOX.east)continue;const t=new Date(slotDate);if(acq&&Number.isFinite(Number(acq[i]))){const q=Number(acq[i]);t.setUTCHours(Math.floor(q/100),q%100,0,0)}out.push({lat:la,lon:lo,time:t,frp:frp?s("FRP",frp[i]):null,conf:conf?s("FIRE_CONFIDENCE",conf[i]):null,area:area?s("PIXEL_SIZE",area[i]):null})}return out}
function rad(a){return Number.isFinite(a)&&a>0?Math.max(5,Math.min(9,Math.sqrt(a)/2)):6}
function render(rows){const g=L.layerGroup();rows.forEach(x=>{const a=age(x.time.getTime()),size=24;const icon=L.divIcon({className:"irrati-meteosat-star",html:`<span class="irrati-meteosat-star-inner" style="color:${a.c}">★</span>`,iconSize:[size,size],iconAnchor:[size/2,size/2],popupAnchor:[0,-size/2]});const m=L.marker([x.lat,x.lon],{icon,pane:"meteosatPane",zIndexOffset:1500,title:`Meteosat FRP-PIXEL · ${a.l}`});const frp=x.frp==null?"—":`${x.frp.toFixed(1)} MW`,conf=x.conf==null?"—":`${Math.round(x.conf)}%`,area=x.area==null?"—":`${(x.area/100).toFixed(2)} km²`;m.bindPopup(`<strong>🛰️ Meteosat FRP-PIXEL</strong><br>Observación: ${fmt(x.time)}<br>Antigüedad: ${a.l}<br>FRP: ${frp}<br>Confianza: ${conf}<br>Área efectiva: ${area}<br>Lat/Lon: ${x.lat.toFixed(4)}, ${x.lon.toFixed(4)}`);g.addLayer(m)});g.addTo(map);return g}
async function fetchSlot(d){const k=d.getTime();if(files.has(k))return files.get(k).count;try{const r=await fetch(`${API}?slot=${slot(d)}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const ab=await r.arrayBuffer(),M=await h5.ready,name=`frp_${k}.h5`;M.FS.writeFile(name,new Uint8Array(ab));const f=new h5.File(name,"r"),rows=parse(f,d);f.close();try{M.FS.unlink(name)}catch{}const layer=render(rows);files.set(k,{count:rows.length,layer,slot:new Date(d)});return rows.length}catch(e){console.warn("Meteosat",slot(d),e);return-1}}
function purge(){const cut=Date.now()-HISTORY;files.forEach((v,k)=>{if(k<cut){try{map.removeLayer(v.layer)}catch{}files.delete(k)}})}
function recolor(){files.forEach(v=>v.layer.eachLayer(m=>{const a=age(v.slot.getTime()),el=m.getElement?.()?.querySelector(".irrati-meteosat-star-inner");if(el)el.style.color=a.c}))}
async function load(){if(loading||!enabled)return;loading=true;try{status("Meteosat: conectando con FRP-PIXEL…");await loadH5();const latest=r15(new Date(Date.now()-LATENCY)),hour=rh(latest),slots=[latest];for(let t=hour.getTime()-HOUR;t>=hour.getTime()-HISTORY;t-=HOUR)slots.push(new Date(t));let done=0,det=0,miss=0,cursor=0;const worker=async()=>{while(cursor<slots.length&&enabled){const d=slots[cursor++],n=await fetchSlot(d);done++;if(n<0)miss++;else det+=n;if(done%5===0||done===slots.length)status(`Meteosat: ${done}/${slots.length} observaciones · ${det} detecciones${miss?` · ${miss} sin datos`:""}`)}};await Promise.all([worker(),worker(),worker(),worker()]);purge();recolor();$("irratiMeteosatTime").textContent=`Último slot: ${fmt(latest)} local`;status(`Meteosat: ${Array.from(files.values()).reduce((n,v)=>n+v.count,0)} detecciones visibles${miss?` · ${miss} horas sin datos`:""}`,"ok")}catch(e){console.error(e);status(`Meteosat: error — ${e.message||e}`,"error")}finally{loading=false}}
function schedule(){if(timer)clearTimeout(timer);const now=Date.now(),next=(Math.floor(now/REFRESH)+1)*REFRESH+4000;timer=setTimeout(async()=>{timer=null;if(enabled){await load();schedule()}},Math.max(5000,next-now))}
async function toggle(on){enabled=!!on;panel();$("irratiMeteosatPanel").style.display=on?"block":"none";if(!on){if(timer)clearTimeout(timer);files.forEach(v=>{try{map.removeLayer(v.layer)}catch{}});files.clear();timer=null;window.IrratiGISMeteosatLayer=null;status("Meteosat apagado");return}pane();await load();window.IrratiGISMeteosatLayer={toggle};schedule()}
function row(){document.querySelectorAll(".leaflet-control-layers-overlays").forEach(list=>{if(list.querySelector(".irrati-meteosat-layer-row"))return;const r=document.createElement("label");r.className="irrati-meteosat-layer-row";r.style.display="block";const i=document.createElement("input");i.type="checkbox";i.className="leaflet-control-layers-selector";i.checked=enabled;i.onchange=()=>toggle(i.checked);const s=document.createElement("span");s.textContent=" 🛰️ Meteosat FRP · antigüedad";r.append(i,s);list.appendChild(r)})}
function styles(){if($("irratiMeteosatStyle"))return;const s=document.createElement("style");s.id="irratiMeteosatStyle";s.textContent=`.irrati-meteosat-panel{position:absolute;left:10px;bottom:58px;z-index:1002;width:min(270px,calc(100vw - 20px));background:#fff;border-radius:10px;box-shadow:0 2px 12px rgba(0,0,0,.22);padding:7px;font:11px system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#1c2d24}.irrati-meteosat-head{display:flex;justify-content:space-between;align-items:center}.irrati-meteosat-head strong{font-size:12px}.irrati-meteosat-head button{border:0;background:#eef3ef;border-radius:7px;padding:4px 8px;cursor:pointer}.irrati-meteosat-sub,.irrati-meteosat-note{color:#65736b;margin-top:3px}.irrati-meteosat-legend{display:grid;grid-template-columns:repeat(2,1fr);gap:5px;margin-top:6px}.irrati-meteosat-legend span{display:flex;align-items:center;gap:4px;font-size:9px;font-weight:800;color:#46564d}.irrati-meteosat-legend i{display:inline-flex;width:16px;height:16px;align-items:center;justify-content:center;font-style:normal;font-size:15px;line-height:1}.irrati-meteosat-legend .fresh{color:#e31a1c}.irrati-meteosat-legend .recent{color:#ff8c00}.irrati-meteosat-legend .old{color:#ffd21f;text-shadow:0 0 1px #777}.irrati-meteosat-legend .oldest{color:#8b8b8b}.irrati-meteosat-star{background:transparent!important;border:0!important}.irrati-meteosat-star-inner{display:block;width:24px;height:24px;font-size:23px;line-height:24px;text-align:center;text-shadow:-1px -1px 0 #fff,1px -1px 0 #fff,-1px 1px 0 #fff,1px 1px 0 #fff,0 1px 4px rgba(0,0,0,.55)}.irrati-meteosat-time{margin-top:6px;font-weight:800;color:#334b3e}.irrati-meteosat-status{margin-top:4px}.irrati-meteosat-note{font-size:9px;line-height:1.3}`;document.head.appendChild(s)}
function boot(){map=getMap();if(!map){setTimeout(boot,500);return}styles();panel();row();new MutationObserver(row).observe(document.body,{childList:true,subtree:true});window.IrratiGISMeteosat={toggle}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
})();
