(()=>{
"use strict";
const WMS="https://adaguc.lsasvcs.ipma.pt//adagucserver";
const DATASET="MSG-FRP";
const DEFAULT_BBOX=[-5.0,42.3,-0.8,44.0];
let map=null, layer=null, info=null, times=[], rangeHours=24, index=0, busy=false, enabled=false;
const $=id=>document.getElementById(id);
function getMap(){return window.IrratiGISMap||((typeof window.map!=="undefined")?window.map:null)}
function esc(s){return String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]))}
function round15(d){const x=new Date(d);x.setUTCSeconds(0,0);x.setUTCMinutes(Math.floor(x.getUTCMinutes()/15)*15);return x}
function iso(d){return d.toISOString().replace(/\.000Z$/,"Z")}
function fmt(d){return new Intl.DateTimeFormat("es-ES",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Madrid"}).format(d)}
function childText(el,name){return [...(el?.children||[])].find(x=>x.localName===name)?.textContent?.trim()||""}
function parseTimeExtent(layerEl){const nodes=[...layerEl.getElementsByTagName("Dimension"),...layerEl.getElementsByTagName("Extent")];const n=nodes.find(x=>(x.getAttribute("name")||"").toLowerCase()==="time");if(!n)return null;return n.textContent.replace(/\s+/g," ").trim()}
function parseIsoDuration(s){const m=String(s).match(/^P(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?)?$/);if(!m)return 15*60000;return (((+m[1]||0)*24+(+m[2]||0))*60+(+m[3]||0))*60000||15*60000}
function parseCaps(xmlText){const xml=new DOMParser().parseFromString(xmlText,"text/xml");if(xml.getElementsByTagName("parsererror").length)throw Error("GetCapabilities devolvió XML inválido");const ls=[...xml.getElementsByTagName("Layer")];const target=ls.find(l=>/FRP-PIXEL/i.test(childText(l,"Title"))||/FRP-PIXEL/i.test(childText(l,"Abstract"))||/FRP-PIXEL/i.test(childText(l,"Name")));if(!target)throw Error("No se encontró la capa MSG FRP-PIXEL");const name=childText(target,"Name");const raw=parseTimeExtent(target);if(!name)throw Error("La capa FRP-PIXEL no tiene Name");if(!raw)throw Error("La capa FRP-PIXEL no tiene dimensión TIME");return {name,title:childText(target,"Title")||name,rawTime:raw,layer:target}}
function latestFromExtent(raw){const p=String(raw).split(/[;,]/).map(x=>x.trim()).filter(Boolean);let end=p[p.length-1]||"";if(end.includes("/")){const a=end.split("/");end=a[1]||a[0]}const d=new Date(end);return Number.isFinite(d.getTime())?round15(new Date(Math.min(d.getTime(),Date.now()))):round15(new Date(Date.now()-30*60000))}
function buildTimes(hours,latest){const end=latest||round15(new Date(Date.now()-30*60000));const n=Math.round(hours*4);const start=new Date(end.getTime()-hours*3600000);const out=[];for(let i=0;i<=n;i++)out.push(new Date(start.getTime()+i*15*60000));return out}
function mapUrl(t){const p=new URLSearchParams({dataset:DATASET,SERVICE:"WMS",VERSION:"1.1.1",REQUEST:"GetMap",LAYERS:info.name,STYLES:"",SRS:"EPSG:4326",BBOX:DEFAULT_BBOX.join(","),WIDTH:"1200",HEIGHT:"680",FORMAT:"image/png",TRANSPARENT:"TRUE",TIME:iso(t),_irrati:Date.now().toString()});return WMS+"?"+p.toString()}
function status(t,type="info"){const e=$("irratiMeteosatStatus");if(!e)return;e.textContent=t;e.dataset.type=type;e.style.color=type==="error"?"#a12626":type==="ok"?"#176b43":"#52645a"}
function ensurePane(){if(!map.getPane("meteosatPane")){const p=map.createPane("meteosatPane");p.style.zIndex=350}}
function setOverlay(t){if(!map||!info)return;busy=true;status(`Meteosat: cargando ${fmt(t)}…`);const url=mapUrl(t);const next=L.imageOverlay(url,[[DEFAULT_BBOX[1],DEFAULT_BBOX[0]],[DEFAULT_BBOX[3],DEFAULT_BBOX[2]]],{opacity:.78,alt:"Meteosat MSG FRP-PIXEL",zIndex:350,pane:"meteosatPane",crossOrigin:false});let done=false;const finish=(ok)=>{if(done)return;done=true;busy=false;if(ok){if(layer)map.removeLayer(layer);layer=next;layer.addTo(map);window.IrratiGISMeteosatLayer=layer;status(`Meteosat FRP-PIXEL · ${fmt(t)} · intervalo 15 min`,"ok")}else{try{map.removeLayer(next)}catch{};status(`Meteosat: sin imagen disponible para ${fmt(t)}.` ,"error")}updateUi()};next.once("load",()=>finish(true));next.once("error",()=>finish(false));next.addTo(map);setTimeout(()=>finish(false),10000)}
function updateUi(){const s=$("irratiMeteosatSlider"),v=$("irratiMeteosatTime");if(s){s.max=Math.max(0,times.length-1);s.value=index}if(v&&times[index])v.textContent=fmt(times[index])+" UTC "+(Intl.DateTimeFormat("es-ES",{timeZone:"Europe/Madrid",timeStyle:"short"}).format(times[index])+" local")}
function choose(i){if(!times.length||busy)return;index=Math.max(0,Math.min(times.length-1,+i));updateUi();if(enabled)setOverlay(times[index])}
function setRange(h){rangeHours=h;const latest=latestFromExtent(info.rawTime);times=buildTimes(h,latest);index=times.length-1;[24,48,72].forEach(x=>$("irratiMeteosatR"+x)?.classList.toggle("active",x===h));updateUi();if(enabled)setOverlay(times[index])}
async function loadInfo(){if(info)return info;status("Meteosat: consultando GetCapabilities…");const r=await fetch(WMS+"?dataset="+encodeURIComponent(DATASET)+"&SERVICE=WMS&REQUEST=GetCapabilities&_irrati="+Date.now(),{cache:"no-store",mode:"cors"});const text=await r.text();if(!r.ok)throw Error("GetCapabilities HTTP "+r.status);info=parseCaps(text);status(`Meteosat: capa ${info.name} disponible`,"ok");return info}
function makePanel(){if($("irratiMeteosatPanel"))return;const c=document.createElement("div");c.id="irratiMeteosatPanel";c.className="irrati-meteosat-panel leaflet-control";c.innerHTML=`<div class="irrati-meteosat-head"><strong>🛰️ Meteosat · FRP-PIXEL</strong><button id="irratiMeteosatClose" type="button">×</button></div><div class="irrati-meteosat-sub">SEVIRI/MSG · observación cada 15 min</div><div class="irrati-meteosat-ranges"><button id="irratiMeteosatR24" type="button" class="active">24 h</button><button id="irratiMeteosatR48" type="button">48 h</button><button id="irratiMeteosatR72" type="button">72 h</button></div><div class="irrati-meteosat-time" id="irratiMeteosatTime">—</div><input id="irratiMeteosatSlider" type="range" min="0" max="0" value="0" step="1"><div class="irrati-meteosat-nav"><button id="irratiMeteosatPrev" type="button">◀ 15 min</button><button id="irratiMeteosatNext" type="button">15 min ▶</button></div><div id="irratiMeteosatStatus" class="irrati-meteosat-status">Meteosat apagado</div><div class="irrati-meteosat-note">Fuente: LSA SAF / EUMETSAT · FRP-PIXEL LSA-502 · 3 km</div></div>`;map.getContainer().appendChild(c);$("irratiMeteosatClose").onclick=()=>toggle(false);$("irratiMeteosatSlider").oninput=e=>choose(e.target.value);$("irratiMeteosatPrev").onclick=()=>choose(index-1);$("irratiMeteosatNext").onclick=()=>choose(index+1);[24,48,72].forEach(h=>$("irratiMeteosatR"+h).onclick=()=>setRange(h));}
async function toggle(on){enabled=!!on;makePanel();$("irratiMeteosatPanel").style.display=on?"block":"none";if(!on){if(layer){map.removeLayer(layer);layer=null}status("Meteosat apagado");window.IrratiGISMeteosatLayer=null;return}try{await loadInfo();ensurePane();setRange(rangeHours)}catch(e){status("Meteosat: "+(e.message||e),"error");}}
function addLayerRow(){const lists=document.querySelectorAll(".leaflet-control-layers-overlays");if(!lists.length)return false;lists.forEach(list=>{if(list.querySelector(".irrati-meteosat-layer-row"))return;const row=document.createElement("label");row.className="irrati-meteosat-layer-row";row.style.display="block";const input=document.createElement("input");input.type="checkbox";input.className="leaflet-control-layers-selector";input.checked=enabled;input.addEventListener("change",()=>toggle(input.checked));const span=document.createElement("span");span.textContent=" 🛰️ Meteosat FRP · 15 min";row.appendChild(input);row.appendChild(span);list.appendChild(row)});return true}
function injectStyle(){if($("irratiMeteosatStyle"))return;const s=document.createElement("style");s.id="irratiMeteosatStyle";s.textContent=`.irrati-meteosat-panel{position:absolute;left:10px;bottom:42px;z-index:1002;width:min(390px,calc(100vw - 30px));background:#fff;border-radius:12px;box-shadow:0 3px 18px rgba(0,0,0,.25);padding:11px;font:12px system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#1c2d24}.irrati-meteosat-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.irrati-meteosat-head strong{font-size:14px}.irrati-meteosat-head button{border:0;background:#eef3ef;border-radius:7px;padding:4px 8px;cursor:pointer}.irrati-meteosat-sub,.irrati-meteosat-note{color:#65736b;margin-top:4px}.irrati-meteosat-ranges{display:flex;gap:6px;margin-top:9px}.irrati-meteosat-ranges button,.irrati-meteosat-nav button{border:0;border-radius:8px;background:#edf3ef;color:#234233;padding:7px 9px;font-weight:800;cursor:pointer}.irrati-meteosat-ranges button.active{background:#176b43;color:#fff}.irrati-meteosat-time{font-weight:800;text-align:center;margin:10px 0 4px}.irrati-meteosat-panel input[type=range]{width:100%}.irrati-meteosat-nav{display:flex;justify-content:space-between;gap:6px;margin-top:5px}.irrati-meteosat-nav button{flex:1}.irrati-meteosat-status{margin-top:8px;padding:6px 8px;background:#f7faf8;border-radius:8px;font-weight:700}.irrati-meteosat-note{font-size:10px;margin-top:7px}@media(max-width:520px){.irrati-meteosat-panel{left:7px;bottom:52px;width:calc(100vw - 20px)}}`;document.head.appendChild(s)}
function boot(){map=getMap();if(!map||typeof L==="undefined"){setTimeout(boot,500);return}injectStyle();makePanel();addLayerRow();if(!window.__irratiMeteosatObserver){window.__irratiMeteosatObserver=new MutationObserver(()=>addLayerRow());window.__irratiMeteosatObserver.observe(document.body,{childList:true,subtree:true})}}
window.IrratiGISMeteosat={toggle,setRange,choose};boot();
})();
